### ISSUE TITLE
Hi, I'm getting this error

### ISSUE THREAD

**Issue by luchi17** [muxinc/mux-stats-sdk-kaltura-ios#49]
While trying to import MUXSDKKaltura I get this error. 

I'm installing it with cocoa pods

![Screenshot 2023-02-03 at 15 11 35](https://user-images.githubusercontent.com/25434704/216624606-636ae1ab-20bd-468d-a15f-f3475859ddf0.png)

**Comment by daytime-em** [comment]
There should be an update for this issue going out today. Thank you for your report!

**Comment by daytime-em** [comment]
Hello! Version `2.0.0` was just release with a fix for this issue. Thanks for your patience and again for your report!
